/*
   This file was generated automatically by Alchitry Labs version 1.2.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [8-1:0] M_myCounter_leds;
  blink_2 myCounter (
    .clk(clk),
    .rst(rst),
    .leds(M_myCounter_leds)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = {M_myCounter_leds[0+0-:1], M_myCounter_leds[1+0-:1], M_myCounter_leds[2+0-:1], M_myCounter_leds[3+0-:1], M_myCounter_leds[4+0-:1], M_myCounter_leds[5+0-:1], M_myCounter_leds[6+0-:1], M_myCounter_leds[7+0-:1]};
    usb_tx = usb_rx;
  end
endmodule
