/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] seg,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [4-1:0] M_myCounter_num;
  counter_2 myCounter (
    .clk(clk),
    .rst(rst),
    .num(M_myCounter_num)
  );
  
  wire [8-1:0] M_myDecoder_seg;
  decoder_3 myDecoder (
    .num(M_myCounter_num),
    .seg(M_myDecoder_seg)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    seg = M_myDecoder_seg;
    led = M_myCounter_num;
    usb_tx = usb_rx;
  end
endmodule
