/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module decoder_3 (
    input [3:0] num,
    output reg [7:0] seg
  );
  
  
  
  always @* begin
    
    case (num)
      1'h0: begin
        seg = 1'h0;
      end
      1'h1: begin
        seg = 24'ha98ac7;
      end
      default: begin
        seg = 20'hf69b5;
      end
    endcase
  end
endmodule
